name: Flask CI/CD to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Step 1: Checkout the repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          echo "Installing dependencies ðŸ§ª"
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests using pytest
      - name: Run tests
        run: |
          echo "Tests are running ðŸ§ª"
          python3 -m pytest

      # Step 5: Trigger deployment on Render.com using REST API
      - name: Trigger Render Deploy
        run: |
          echo "Deploying ðŸ§ª"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_DEPLOY_HOOK }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            https://api.render.com/v1/services/srv-d1006p0gjchc73a7ek0g/deploys
